---
- hosts: docker

  tasks:
  - name: stop container
    command: docker stop regapp
    
  - name: delete container
    command: docker rm regapp
    
  - name: delete image
    command: docker rmi gauravlab01/regapp
    
  - name: pull docker image
    command: docker pull gauravlab01/regapp:latest

  - name: create container from pulled image
    command: docker run -d --name regapp-25022022 -p 8081:8080 -t gauravlab01/regapp:latest
